# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  border: rounded
  filterMode: fuzzy
  nerdFontsVersion: "3"
  showCommandLog: false
  theme:
    activeBorderColor:
      - "#7fe0ff"
      - bold
    inactiveBorderColor:
      - "#839b9e"
    searchingActiveBorderColor:
      - "#22b8f5"
      - bold
    optionsTextColor:
      - "#a8ecff"
    selectedLineBgColor:
      - "#0f526f"
    cherryPickedCommitBgColor:
      - "#214c5e"
    cherryPickedCommitFgColor:
      - "#5ff2cf"
    markedBaseCommitBgColor:
      - "#0d3547"
    markedBaseCommitFgColor:
      - "#ffd873"
    unstagedChangesColor:
      - "#ff7a6e"
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never
